export default {
  /**
   * 客户档案查询页面
   */
  customer: {
    tit1: 'Retrieval',
    tit2: 'Custom search terms',
    label1: 'Mobile/phone',
    label2: 'File number',
    label3: 'The main consulting project',
    label4: 'Consultation project',
    label5: 'Date of visit',
    label6: 'Last visit',
    label7: 'Registered date',
    label8: 'Last consultation',
    label9: 'home status',
    label10: 'Has been on the door',
    label11: 'No door',
    label12: 'Consumer status',
    label13: 'has been traded',
    label14: 'Not traded',
    label15: 'WeChat status',
    label16: 'Binding',
    label17: 'Unbound',
    label18: 'Net revenue total {min}',
    label19: 'Customer group',
    label20: 'Result set',
    label21: 'label',
    label22: 'Reservation date',
    label23: 'Custom field',
    label24: 'Custom content',
    label25: 'To the hospital',
    label26: 'Appointment hospital',
    label27: 'Newly diagnosed hospital',
    label28: 'Registered hospital',
    label29: 'registration personnel',
    label30: 'Net revenue total {max}',
    label31: 'distribution channel',
    valid1: 'Please select a custom field first!',
    valid2: 'Please enter the number!',
    placeholder1: 'Please select the label',
    placeholder2: 'Please select a date',
  },


	/**
   * 客户档案主结构
   */
  customerIndex: {
   more: 'more'
  },
	

   /**
   * 客户档案
   */
   customerMsg: {
    label1: 'Unbound WeChat',
    label2: 'Binding WeChat:',
    label3: 'Binding time:',
    label4: 'Contact method{0}',
    label5: 'Mobile Phone',
    label6: 'Backup phone',
    label7: 'Address',
    label8: 'File number',
    label9: 'Remarks',
    label10: 'area',
    label11: 'birthday',
    label12: 'Customer channel',
    label13: 'registrant',
    label14: 'Recommend people',
    label15: 'Recommendation channel',
    label16: 'Source',
    label17: 'Member Information',
    label18: 'Customer service information',
    label19: 'On-site consultation',
    label20: 'Consultation project',
    label21: 'Customer characteristics',
    label22: 'Has been on the door',
    label23: 'No door customer',
    label24: 'Already sold customers',
    label25: 'Uncompleted customers',
    label26: 'There is a complaint record',
    label27: 'Blacklist members',
    label28: 'Wechat has been bundled',
    label29: 'Service Information',
    label30: 'Date of visit',
    label31: 'Newly diagnosed hospital',
    label32: 'last consultation',
    label33: 'Recently visited',
    label34: 'Registration time',
    label35: 'Extension information',
    label36: 'Customer label',
    label37: 'Customer group',
    label38: 'SMS template',
    label39: 'Template content:',
    label40: 'Number of parameters:',
    label41: 'Parameter description:',
    label42: 'Parameter description: parameter input $CustomerName automatically read customer name',
    label43: 'Parameter {0}',
    label44: 'brand',
    label45: 'contact',
    label46: 'address',
    btn: 'send messages',
    modalTit1: 'Modify customer information',
    modalTit2: 'Modify customer defined information',
    modalTit3: 'Send SMS',
    modalTit4: 'modify source',
    modalTit5: 'modify the consulting project',
    modalTit6: 'Modify channel',
    modalTit7: 'modify alternate contact',
    placeholder1: 'Select birthday date',
    valid1: 'Please type in your name',
    valid2: 'please select the region',
    valid3: 'Please select message template',
    msg1: 'No edit contact rights! ',
    msg2: 'Is sure to contact the customer? ',
    msg3: 'Customer information:',
    tit1: 'tag details',
    tit2: 'Group details',
  },


  /**
   * 添加标签
   */
  tagAdd: {
    label1: 'Label',
    label2: 'Label group',
    label3: 'Lookup label',
    placeholder: 'Please enter the name of the label',
    valid: 'Please select the label',
  },
  /**
   * 标签管理
   */
  tagInfo: {
    colTit1: 'Add users',
    colTit2: 'Add time',
    msg: 'Is it sure to delete this label?',
  },


  /**
   * 添加客户组
   */
  groupAdd: {
    colTit: 'Client group name',
    msg: 'Do you want to delete this customer group?',
  },


  /**
   * 客户二维码
   */
  qartCode: {
    msg: 'The two-dimensional code is generated by the user ID and used for subsequent user card production.',
  },


  /**
   * 添加渠道佣金
   */
  commissionAdd: {
    label: 'Commission amount',
    valid: 'Please enter the commission amount',
  },
  /**
   * 客户渠道信息
   */
  indexStore: {
    tit: 'Channel information',
    label1: 'numbered',
    label2: 'contact',
    label3: 'mobile phone',
    label4: 'address',
    label5: 'account name',
    label6: 'open account',
    label7: 'bank card number',
    colTit1: 'submission time',
    colTit2: 'Submit user',
    colTit3: 'channel',
    colTit4: 'sum',
    msg1: 'aggregate:',
    msg2: 'amount:',
    msg3: 'make sure to delete this click commission? ',
  },


  /**
   * 添加客户头像
   */
  avatarInfo: {
    label: 'select the head image',
    tit: 'view the picture',
    valid: 'please choose pictures',
    msg1: "head size can't be more than 10M! ",
    msg2: 'please select GIF, JPG, JPEG, BMP, PNG pictures! ',
  },


  /**
   * 赠送积分
   */
  pointAdd: {
    label1: 'existing integral',
    label2: 'gift integral',
    valid: 'please enter integral',
  },
  /**
   * 扣减积分
   */
  pointRebate: {
    label: 'Deduction integral'
  },


  /**
   * 积分兑换券
   */
  pointCoupon: {
    label1: 'convertibility integral',
    label2: 'voucher',
    label3: 'voucher amount',
    colTit: 'can use the hospital',
    valid1: 'please enter the convertibility point',
    valid2: 'please enter the amount of voucher',
    valid3: 'please choose voucher,'
  },


  /**
   * 添加会员
   */
  memberAdd: {
    label: 'Member type',
    valid: 'Please choose the type of membership',
  },


  /**
   * 添加会员权益
   */
  equityAdd: {
    label: 'Rights and interests',
    valid: 'Please choose the rights and interests',
  },


  /** 
   * 会员权益列表页面
   */
  indexMember: {
    tit1: 'member records',
    tit2: 'list of rights and interests',
    colTit1: 'member type',
    colTit2: 'operating time',
    colTit3: 'operating user',
    colTit4: 'note',
  },


  /** 
   * 送券页面
   */
  couponOrderAdd: {
    label1: 'voucher type',
    label2: 'sum',
    valid1: 'please input the amount',
    valid2: 'please choose voucher,',
    colTit: 'can use the hospital',
  },
  /** 
   * 退券页面
   */
  couponRebateOrderAdd: {
    colTit1: 'voucher number',
    colTit2: 'voucher type',
    colTit3: 'hospital',
    colTit4: 'sum',
    colTit5: 'residual amount',
    colTit6: 'expiry time',
    colTit7: 'valid',
    colTit8: 'has expired',
  },


  /** 
   * 账号情况
   */
  indexAccount: {
    tit1: 'account situation',
    tit2: 'pre payment',
    tit3: 'voucher',
    tit4: 'integral',
    tit5: 'change of receivables',
    tit6: 'voucher change',
    label1: 'balance',
    label2: 'voucher amount',
    label3: 'aggregate',
    depositType1: 'pre - receivable recharge',
    depositType2: 'refund',
    depositType4: 'transfer',
    couType1: 'Posiple Stand Posiple Studio',
    couType2: 'SouthType',
    couType3: 'South-TouthTimes',
    couType4: 'South-Posiple',
    pointType11: 'handmade gift',
    pointType12: 'consumptive gift',
    pointType21: 'manual deductions',
    pointType22: 'voucher',
    pointType23: 'exchange of products',
    pointType24: 'refund deductions',
    pointType25: 'withdrawal deduction',
    colTit1: 'time',
    colTit2: 'hospital',
    colTit3: 'acquisition mode',
    colTit4: 'pre receivable number',
    colTit5: 'sum',
    colTit6: 'residual amount',
    colTit7: 'operator',
    colTit8: 'voucher number',
    colTit9: 'expiry time',
    colTit10: 'valid',
    colTit11: 'has expired',
    colTit12: 'Number',
    colTit13: 'variable type',
    colTit14: 'pre - receivable type',
    colTit15: 'pre receivable number',
    colTit16: 'voucher type',
    colTit17: 'voucher number',
  },


  /** 
   * 添加客户关系页面
   */
  relationAdd: {
    label1: 'relationship',
    label2: 'associated customer number',
    valid1: 'Please enter the correct customer number',
    valid2: 'please select the relationship type',
  },
  /** 
   * 客户关系页面
   */
  indexRelation: {
    tit1: 'customer relationship',
    tit2: 'recommender',
    colTit1: 'customer',
    colTit2: 'submission time',
    colTit3: 'Submit user',
    colTit4: 'recommendation number',
    msg: 'Is it sure to cancel this relationship?',
  },


  /** 
   * 添加黑名单
   */
  blacklistOrderAdd: {
    label: 'Reason',
    valid: 'Please fill in the reason',
  },


  /** 
   * 开发人员变更
   */
  exploitChangeInfo: {
    label1: 'change type',
    label2: 'current developer',
    label3: 'new developer',
    label4: 'cause of change',
    valid1: 'please choose the new developer',
    valid2: 'please fill in the cause of the change',
  },


  /** 
   * 咨询人员变更
   */
  managerChangeInfo: {
    label1: 'Current Consultants',
    label2: 'New consultants',
    valid: 'Please choose a new consultant',
  },


  /** 
   * 更换医生
   */
  orderDetailManagerAdd: {
    label1: 'project',
    label2: 'new doctor',
    valid1: 'please select project',
    valid2: 'please choose a doctor',
    colTit1: 'order date',
    colTit2: 'project name',
    colTit3: 'quantity',
    colTit4: 'single user',
    colTit5: 'master doctor',
  },


  /** 
   * 添加咨询
   */
  consultAdd: {
    label1: 'mode',
    label2: 'consulting project',
    label3: 'consulting content',
    valid1: 'please choose the way',
    valid2: 'please select the consulting project',
    valid3: 'please fill in the advisory content',
    placeholder: 'please choose, you can choose multiple, sort the order',
  },
  /** 
   * 咨询列表页面
   */
  indexConsult: {
    colTit1: 'submission time',
    colTit2: 'submit to the hospital',
    colTit3: 'Submit user',
    tit: 'modification of consultation information',
    msg: 'determine to delete this information? ',
  },


  /** 
   * 添加回访页面
   */
  callbackAdd: {
    label1: 'return type',
    label2: 'return visit mode',
    label3: 'return to the content',
    valid1: 'please choose to return type',
    valid2: 'please choose the way back to visit',
    valid3: 'please fill in the return visit',
  },
  /** 
   * 修改回访页面
   */
  callbackUpdate: {
    label1: 'submission time',
    label2: 'Submit user',
  },
  /** 
   * 添加回访提醒页面
   */
  callbackTaskAdd: {
    label1: 'return date',
    label2: 'reminding the content',
    label3: 'return visitors',
    valid1: 'please choose the date of return visit',
    valid2: 'please fill in the reminders',
    valid3: 'please choose the visitors',
  },
  /** 
   * 添加回访计划
   */
  callbackSetAdd: {
    valid1: 'Please choose the return visit plan',
    valid2: 'Please select the reminder type',
  },
  /** 
   * 回访信息列表
   */
  indexCallback: {
    colTit1: 'reminding the date',
    colTit2: 'reminds users',
    colTit3: 'unfinished',
    colTit4: 'has been completed',
    colTit5: 'return visit time',
    colTit6: 'reminder to create users',
    colTit7: 'reminds creation time',
    tit1: 'modify the return visit information',
    tit2: 'modify the revisit message',
    msg1: 'determine to delete this return message? ',
    msg2: 'sure delete this return call reminder? ',
  },


  /** 
   * 问卷类型页面
   */
  selectSurvey: {
    tit: 'Selection of questionnaire type',
    btn: 'Choice',
  },
  /** 
   * 添加问卷页面
   */
  surveyAdd: {
    label1: 'questionnaire type',
    label2: 'title',
    label3: 'title number',
    label4: 'title',
    label5: 'single election problem',
    label6: 'multiple selection problem',
    label7: 'fill in the blanks',
    label8: 'option {0}:',
    label9: 'answer',
    valid: 'please fill in the answer! ',
  },
  /** 
   * 问卷列表页面
   */
  indexSurvey: {
    colTit1: 'submission time',
    colTit2: 'submit to the hospital',
    colTit3: 'Submit user',
    colTit4: 'questionnaire type',
    btn: 'view',
    tit1: 'revised questionnaire',
    tit2: 'check out the questionnaire',
    msg: 'determine the deletion of this questionnaire? ',
  },
  /** 
   * 查看问卷页面
   */
  surveyView: {
    label: 'answer：'
  },


  /** 
   * 病例模板页面
   */
  selectMedicalRecord: {
    tit: 'Selection of case template',
    btn: 'Choice',
    msg: 'Note: this page will lose the case template format after enabling the translation function.'
  },
  /** 
   * 添加电子病例
   */
  medicalRecordAdd: {
    label1: 'questionnaire type',
    label2: 'medical record number',
    label3: 'default uses BL + hospital ID + date + 4 digit',
    label4: 'store location',
    label5: 'project',
    label6: 'fill in',
  },
  /** 
   * 电子病例列表
   */
  indexMedicalRecord: {
    colTit1: 'submission time',
    colTit2: 'Submit user',
    colTit3: 'case history type',
    colTit4: 'medical record number',
    colTit5: 'store location',
    tit: 'modification of electronic cases',
    msg: 'determine to delete this electronic proportion record? '
  },


  /** 
   * 添加照片
   */
  photoAdd: {
    label1: 'date',
    label2: 'type',
    label3: 'consulting project',
    label4: 'treatment project',
    label5: 'select photos',
    label6: 'consulting',
    label7: 'before treatment',
    label8: 'therapy',
    label9: 'after treatment',
    label10: 'other',
    valid1: 'please select information! ',
    valid2: 'please choose pictures! ',
    valid3: "head size can't be more than 10M! ",
    valid4: 'please select GIF, JPG, JPEG, BMP, PNG pictures! ',
    msg1: 'view picture',
    msg2: 'Select the specified project',
  },
  /** 
   * 照片管理列表
   */
  indexPhoto: {
    label: 'Treatment',
    btn: 'Original map',
    msg: 'Make sure to delete this picture information',
    tit: 'Photo information'
  },
  /** 
   * 编辑照片
   */
  photoUpdate: {
    label1: 'photo',
    label2: 'Submit user',
  },


  /** 
   * 补划扣
   */
  operationAdd: {
    label1: 'date of deduction',
    label2: 'list of items to be deducted',
    colTit1: 'project name',
    colTit2: 'order hospital',
    colTit3: 'order date',
    colTit4: 'master doctor',
    colTit5: 'purchase quantity',
    colTit6: 'residual quantity',
    colTit7: 'deduct quantity',
    valid1: 'please select the buckle project',
    valid2: 'please choose a doctor',
    valid3: 'please choose the date',
  },
  /** 
   * 划扣列表
   */
  indexOperation: {
    colTit1: 'operating time',
    colTit2: 'operating hospital',
    colTit3: 'operating user',
    colTit4: 'project name',
    colTit5: 'order date',
    colTit6: 'quantity',
    colTit7: 'doctor',
    btn: 'revocation',
    msg: 'determined to revoke the deduction of information',
    tit: 'modification and deduction',
  },
  /** 
   * 编辑划扣
   */
  operationUpdate: {
    colTit: 'Division of labor',
    btn: 'Add a doctor',
    valid: 'Please choose a doctor',
  },


  /** 
   * 欠款划扣
   */
  debtOperationAdd: {
    label1: 'project',
    label2: 'quantity',
    label3: 'cause',
    valid1: 'please select project',
    valid2: 'please choose the number',
    colTit1: 'order date',
    colTit2: 'residual quantity',
    colTit3: 'transaction amount',
    colTit4: 'Arrears',
  },


  /** 
   * 添加咨询预约
   */
  appointmentAdd: {
    label1: 'choose the hospital',
    label2: 'appointment date',
    label3: 'reservation time',
    label4: 'reservations for consultants',
    valid1: 'please choose the hospital',
    valid2: 'please choose the appointment date',
    valid3: 'please choose the appointment time',
    valid4: 'please choose an appointment Consultant',
  },
  /** 
   * 预约列表
   */
  indexAppointment: {
    tit1: 'consultation reservation',
    tit2: 'treatment reservation',
    tit3: 'operation reservation',
    tit4: 'edit and consult reservations',
    tit5: 'edit treatment reservation',
    tit6: 'edit operation reservation',
    colTit1: 'reservation code',
    colTit2: 'has been home',
    colTit3: 'no door',
    colTit4: 'submission time',
    colTit5: 'Submit user',
    colTit6: 'Under line',
    colTit7: 'Online APP',
    colTit8: 'Have been cancelled',
    colTit9: 'make an appointment',
    colTit10: 'start time',
    colTit11: 'End time',
    colTit12: 'unstarted',
    colTit13: 'in the middle',
    colTit14: 'has ended',
    msg: 'Is it sure to cancel this reservation?',
  },
  /** 
   * 添加治疗预约
   */
  treatAdd: {
    label: 'reservations',
    btn1: 'choose the items bought',
    btn2: 'select all the items',
    valid: 'please choose an appointment',
    colTit1: 'order date',
    colTit2: 'quantity',
    colTit3: 'single user',
    colTit4: 'master doctor',
  },
  /** 
   * 添加手术预约
   */
  surgeryAdd: {
    label1: 'type of anaesthesia',
    label2: 'general anesthesia',
    label3: 'local anesthesia',
    valid: 'Please choose a doctor to make an appointment'
  },


  /** 
   * 添加预收款
   */
  depositOrderAdd: {
    msg1: 'total amount:',
    msg2: 'Voucher:',
    tit: 'add the pre - receivable project',
    colTit1: 'price',
    colTit2: 'total',
    colTit3: 'scope of use',
    colTit4: 'voucher',
    colTit5: 'Number',
    valid: 'Please choose the pre payment'
  },
  /** 
   * 查看预收款
   */
  depositOrderView: {
    colTit: 'Pre payment',
    count: 'Total：'
  },
  /** 
   * 退预收款
   */
  depositRebateOrderAdd: {
    msg1: 'refunded pre receipts:',
    msg2: 'note: This is the total amount of the total refunds',
    label: 'refund amount',
    colTit1: 'residual amount',
    colTit2: 'amount of deductions',
  },
  /** 
   * 查看退预收款
   */
  depositRebateOrderView: {
    label1: 'refunds',
    label2: 'audit information',
    label3: 'automatic audit',
    label4: 'detailed',
    colTit1: 'level',
    colTit2: 'audit user',
    colTit3: 'audit time',
    colTit4: 'opinion',
  },


  /** 
   * 添加项目单
   */
  orderAdd: {
    msg1: 'the customer has no discount rights',
    msg2: 'no discounts',
    msg3: 'project has been added, do not repeat it! ',
    msg4: 'add package success, please edit in the list! ',
    input: 'please enter the project name for quick search',
    valid1: 'please select project',
    valid2: 'please choose a doctor',
    label1: 'Discount:',
    label2: 'original price:',
    label3: 'receivable price:',
    label4: 'overall discount:',
    label5: 'name [Specification]',
    label6: 'price',
    label7: 'stock',
    label8: 'set meal',
    label9: 'consumables',
    label10: 'project inventory',
    label11: 'unit price',
    label12: 'quantity',
    label13: 'receivable amount',
    label14: 'choose the doctor',
    colTit1: 'project',
    colTit2: 'set meal',
    colTit3: 'total original price',
    colTit4: 'discount',
  },
  /** 
   * 查看项目单
   */
  orderView: {
    colTit1: 'project number',
    colTit2: 'project name',
    colTit3: 'original price',
    colTit4: 'master doctor',
  },


  /** 
   * 添加退项目
   */
  backOrderAdd: {
    tit1: 'no project',
    tit2: 'drug withdrawal',
    tit3: 'system hints',
    msg: 'note: the refund amount exceeds the actual payment amount of the customer (paid in advance + prepaid)',
    valid1: 'please choose a refund project',
    valid2: 'please choose the drugs',
    label1: 'number of refunded projects:',
    label2: 'amount:',
    label3: 'select project',
    label4: 'deduction integral',
    colTit1: 'project',
    colTit2: 'date of purchase',
    colTit3: 'quantity',
    colTit4: 'total project',
    colTit5: 'real payment',
    colTit6: 'pre payment is paid',
    colTit7: 'voucher',
    colTit8: 'residual quantity',
    colTit9: 'back number',
    colTit10: 'refund',
    colTit10: 'refund',
    colTit11: 'purchase quantity',
    colTit12: 'unreceived quantity',
    colTit13: 'has been retreated',
  },


  /** 
   * 查看还款单
   */
  repaymentOrderView: {
    colTit1: 'amount of arrears',
    colTit2: 'repayment amount',
    colTit3: 'cash',
    colTit4: 'credit card',
  },


  /** 
   * 添加赔款单
   */
  backOperationOrderAdd: {
    label1: 'Total amount of project indemnity',
    label2: 'Selection project',
    label3: 'Deduction integral',
    valid: 'Please choose the indemnity project',
    msg: 'Note: the indemnity amount exceeds the actual payment amount of the customer (paid in advance + prepaid).',
    colTit1: 'project',
    colTit2: 'date of purchase',
    colTit3: 'quantity',
    colTit4: 'total project',
    colTit5: 'real payment',
    colTit6: 'pre payment is paid',
    colTit7: 'voucher',
    colTit8: 'residual quantity',
    colTit9: 'operating time',
    colTit10: 'operating user',
    colTit11: 'use quantity',
    colTit12: 'division of labor',
    colTit13: 'amount of indemnity',
    colTit14: 'number of indemnities',
  },


  /** 
   * 订单列表
   */
  indexOrder: {
    tit1: 'pre - receivable order',
    tit2: 'project order',
    tit3: 'repayment list',
    tit4: 'return project order',
    tit5: 'retreat receivables',
    tit6: 'online order',
    tit7: 'Modifying the project order',
    check1: 'view the pre - receivable order',
    check2: 'view project orders',
    check3: 'check the repayment list',
    check4: 'check out project orders',
    check5: 'check out receivables',
    paid1: 'no payment',
    paid2: 'already paid',
    paid3: 'Arrears',
    audit1: 'to be audited',
    audit2: 'audit through',
    audit3: 'audit does not pass',
    msg1: 'confirm the deletion of this order? ',
    msg2: 'order information:',
    msg3: 'amount:',
    type1: 'to be paid',
    type2: 'has been cancelled',
    type3: 'has been closed',
    type4: 'can be used',
    type5: 'treatment completed',
    type6: 'unevaluated',
    type7: 'has been evaluated',
    type8: 'refunds',
    type9: 'refunds',
    colTit1: 'submit to the hospital',
    colTit2: 'order number',
    colTit3: 'Submit user',
    colTit4: 'submission time',
    colTit5: 'sum',
    colTit6: 'payment state',
    colTit7: 'payment time',
    colTit8: 'Audit status',
    colTit9: 'original price',
    colTit10: 'discount',
    colTit11: 'no discounts',
    colTit12: 'transaction amount',
    colTit13: 'operating hospital',
    colTit14: 'Arrears order number',
    colTit15: 'should be paid in amount',
    colTit16: 'repayment amount',
    colTit17: 'remaining arrears',
    colTit18: 'Operating user',
    colTit19: 'Operation time',
    colTit20: 'commodity name',
    colTit21: 'quantity of goods',
    colTit22: 'residual quantity',
    colTit23: 'order amount',
  },


  /** 
   * 效果追踪模板选择
   */
  customerEffectrRackingtextAdd: {
    tit: 'Select effect tracking template',
  },
  /** 
   * 添加效果追踪
   */
  effectTrackingAdd: {
    label1: 'Tracking template',
    label2: 'Date',
    input: 'Please select the associated project',
    valid: 'Please complete the required form of the template form.',
  },
  /** 
   * 效果追踪列表
   */
  indexEffectrRackingtext: {
    tit1: 'photo list',
    tit2: 'data list',
    tit3: 'edit effect tracking',
    msg: 'Whether to delete this effect trace record',
    btn1: 'download',
    btn2: 'rotate',
  },


  /** 
   * 添加投诉
   */
  groupComplainAdd: {
    label1: 'choose the hospital',
    label2: 'type of complaint',
    label3: 'complaint doctor',
    label4: 'treatment project',
    label5: 'complaint content',
    valid1: 'please choose',
    valid2: 'please fill in the complaint',
    input: 'select the treatment project',
  },


  /** 
   * 投诉反馈
   */
  indexComplain: {
    tit1: 'complaint',
    tit2: 'blacklist',
    msg: 'do you want to cancel the blacklist? ',
    colTit1: 'submission time',
    colTit2: 'Submit user',
    colTit3: 'complaint hospital',
    colTit4: 'complaint doctor',
    colTit5: 'complaint project',
    colTit6: 'complaint content',
    colTit7: 'has been processed',
    colTit8: 'untreated',
    colTit9: 'handles users',
    colTit10: 'processing time',
    colTit11: 'treatment measures',
    colTit12: 'customer feedback',
    colTit13: 'submit to the hospital',
    colTit14: 'cause',
  },


  /** 
   * 添加未成交
   */
  failtureAdd: {
    label1: 'no transaction type',
    label2: 'no transaction cause',
    valid1: 'please choose the non - transaction type',
    valid2: 'please fill in the reasons for no transaction',
  },
  /** 
   * 未成交列表
   */
  indexFailture: {
    colTit1: 'submission time',
    colTit2: 'submit to the hospital',
    colTit3: 'Submit user',
    msg: 'make sure to delete this uncompleted record? ',
    tit: 'amendment has not been done',
  },


  /** 
   * 转账页面
   */
  depositTransferOrderAdd: {
    label1: 'select pre receipts',
    label2: 'sum',
    label3: 'transfer account number',
    label4: 'cause',
    valid1: 'please enter the customer number',
    valid2: 'please choose the pre - receivable',
    colTit1: 'pre receivable number',
    colTit2: 'pre - receivable type',
    colTit3: 'hospital',
    colTit4: 'residual amount',
  },


  /** 
   * 激活券
   */
  activeCoupon: {
    label1: 'voucher code',
    label2: 'voucher activity',
    label3: 'voucher type',
    label4: 'voucher amount',
    label5: 'release time',
    valid: 'please enter the voucher code',
    msg: 'verify success! ',
    btn1: 'Verification',
    btn2: 'activation'
  },


  /** 
   * 消费项目页面
   */
  indexOrderDetail: {
    label1: 'consumption date',
    label2: 'type of consumption',
    label3: 'all',
    label4: 'unfinished',
    label5: 'prescription list',
    input: 'please choose the date of consumption',
    btn: 'prescription',
    msg1: 'total amount of consumption',
    msg2: 'in which cash card receipts',
    msg3: 'pre payment payment',
    msg4: 'voucher payment',
    msg5: 'Arrears',
    msg6: 'refund of the amount',
    colTit1: 'buy a hospital',
    colTit2: 'date of purchase',
    colTit3: 'order number',
    colTit4: 'project number',
    colTit5: 'project name',
    colTit6: 'quantity',
    colTit7: 'has been used in quantity',
    colTit8: 'unfinished quantity',
    colTit9: 'master doctor',
    colTit10: 'single user',
    colTit11: 'transaction amount',
    colTit12: 'cash',
    colTit13: 'credit card',
    colTit14: 'pre receipts use',
    colTit15: 'vouchers are used',
    colTit16: 'Arrears',
    colTit17: 'back number',
    colTit18: 'refund',
  },


  /** 
   * 上门情况
   */
  indexVisit: {
    tit1: 'door-to-door',
    tit2: 'diagnosis',
    tit3: 'Department reception',
    tit4: 'hospitalization records',
    colTit1: 'door time',
    colTit2: 'hospital',
    colTit3: 'receptionist',
    colTit4: 'time of diagnosis',
    colTit5: 'referral user',
    colTit6: 'subscribe to the user',
    colTit7: 'reception time',
    colTit8: 'department',
    colTit9: 'reception user',
    colTit10: 'operating user',
    colTit11: 'in hospital',
    colTit12: 'has been discharged',
    colTit13: 'time of hospitalization',
    colTit14: 'bed',
    colTit15: 'discharge time',
  },


  /** 
   * 负责用户页面
   */
  indexManager: {
    tit1: 'developer',
    tit2: 'consultants',
    tit3: 'deduction of medical staff',
    tit4: 'developer history detailed',
    tit5: 'consultants have a detailed history',
    tit6: 'deduct the history of medical personnel in detail',
    btn: 'details',
    colTit1: 'hospital',
    colTit2: 'user',
    colTit3: 'start time',
    colTit4: 'End time',
  },
  /** 
   * 划扣执行医务人员详细 
   */
  operatorUserInfo: {
    colTit1: 'execution project',
    colTit2: 'execution time',
    colTit3: 'division of labor',
    colTit4: 'evaluation',
    colTit5: 'doctor',
  },


  /** 
   * 耗材成本页面
   */
  indexCost: {
    label: 'aggregate',
    msg: 'determine to delete this consumable record?',
    colTit1: 'consumption date',
    colTit2: 'project number',
    colTit3: 'project name',
    colTit4: 'hospital',
    colTit5: 'warehouse',
    colTit6: 'item number',
    colTit7: 'item name',
    colTit8: 'quantity',
    colTit9: 'unit price',
    colTit10: 'sum',
    colTit11: 'operating user',
    colTit12: 'operating time',
  },


  /** 
   * 短信记录页面
   */
  indexSms: {
    msg: 'SMS sending takes a little time. The state of the message in the send message can wait for a while to refresh the viewing state. ',
    btn: 'refresh state',
    type1: 'send',
    type2: 'not sent',
    type3: 'sends success',
    type4: 'send failure',
    colTit1: 'hospital',
    colTit2: 'send time',
    colTit3: 'send user',
    colTit4: 'SMS template',
    colTit5: 'SMS content',
    colTit6: 'group task',
    colTit7: 'state',
  },


  /** 
   * 审核申请页面
   */
  indexAudit: {
    tit1: 'developer change',
    tit2: 'consultants change',
    tit3: 'doctor changes',
    tit4: 'blacklist',
    tit5: 'member changes',
    tit6: 'increase the interest',
    tit7: 'delete rights',
    tit8: 'pre receivable transfer',
    tit9: 'voucher',
    tit10: 'buckle voucher',
    tit11: 'gift integral',
    tit12: 'deduction integral',
    tit13: 'integral exchange voucher',
    tit14: 'arrears are deducted',
    tit15: 'Audit situation',
    colTit1: 'submission time',
    colTit2: 'submit to the hospital',
    colTit3: 'Submit user',
    colTit4: 'original developer',
    colTit5: 'new developer',
    colTit6: 'cause',
    colTit7: 'audit status',
    colTit8: 'audit through',
    colTit9: 'audit does not pass',
    colTit10: 'to be audited',
    colTit11: 'Audit situation',
    colTit12: 'Automatic audit',
    colTit13: 'former consultants',
    colTit14: 'new consultants',
    colTit15: 'project',
    colTit16: 'doctor of the original',
    colTit17: 'new doctor',
    colTit18: 'original membership type',
    colTit19: 'new member type',
    colTit20: 'Type of rights and interests',
    colTit21: 'transfer customer',
    colTit22: 'pre receivable number',
    colTit23: 'sum',
    colTit24: 'Voucher type',
    colTit25: 'Voucher number',
    colTit26: 'Number of integrals',
    colTit27: 'voucher amount',
    colTit28: 'buckle project',
    colTit29: 'deduct quantity',
    colTit30: 'start quantity',
  },
  /** 
   * 审核情况
   */
  auditInfoView: {
    colTit1: 'level',
    colTit2: 'audit user',
    colTit3: 'audit status',
    colTit4: 'to be audited',
    colTit5: 'audit time',
    colTit6: 'opinion',
  },


  /** 
   * 投诉记录
   */
  complain: {
    tit: 'Complaint information',
    valid: 'Please enter the treatment measures',
    label1: 'date of complaint',
    label2: 'has been processed',
    label3: 'untreated',
    label4: 'Submit a hospital to a hospital',
    colTit1: 'type of complaint',
    colTit2: 'object of complaint',
    colTit3: 'complaint project',
    colTit4: 'complaint content',
    colTit5: 'submission time',
    colTit6: 'Submit user',
    colTit7: 'handles users',
    colTit8: 'processing time',
    colTit9: 'treatment measures',
    colTit10: 'customer feedback',
  },


  /** 
   * 生日提醒
   */
  birthday: {
    label: 'select date',
    btn1: 'today',
    btn2: 'this week',
    btn3: 'this month',
    colTit1: 'birthday',
    colTit2: 'door-to-door state',
    colTit3: 'has been home',
    colTit4: 'no door',
    colTit5: 'transaction status',
    colTit6: 'has done a deal',
    colTit7: 'no deal',
    colTit8: 'date of first diagnosis',
    colTit9: 'last visit',
    colTit10: 'member type',
    colTit11: 'phone',
  },


  /** 
   * 客户归属权变更
   */
  ownership: {
    btn1: 'batch setup developers',
    btn2: 'batches of consultants',
    btn3: 'change',
    label1: 'user',
    label2: 'allocating to new users',
    label3: 'customer list',
    label4: 'import result set',
    colTit1: 'developers belong',
    colTit2: 'consultants belong',
    tit: 'right of belonging allocation',
    input: 'Please enter the customer number, one line and one line',
    valid1: 'please enter customer information',
    valid2: 'please choose users',
  },
};